version: '3.8'

services:
  password-generator:
    build: .
    ports:
      - "5183:5183"
    container_name: password-generator
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
