services:
  password-generator:
    build: .
    ports:
      - "5183:5183"
    container_name: password-generator
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - password-generator-network

networks:
  app-network:
    driver: bridge